# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_transferencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Transferencia(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(606, 480)
        Form.setStyleSheet("background-color: rgb(118, 0, 88)")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(40, 30, 531, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("background-color:rgba(145, 40, 109,0.9)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(210, 40, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgba(145, 40, 109,0.1)")
        self.label.setObjectName("label")
        self.lineEdit_valor = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_valor.setGeometry(QtCore.QRect(170, 210, 221, 31))
        self.lineEdit_valor.setStyleSheet("color: rgb(255,255,255)")
        self.lineEdit_valor.setFrame(True)
        self.lineEdit_valor.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_valor.setObjectName("lineEdit_valor")
        self.lineEdit_destinatario = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_destinatario.setGeometry(QtCore.QRect(170, 150, 221, 31))
        self.lineEdit_destinatario.setStyleSheet("color: rgb(255,255,255)")
        self.lineEdit_destinatario.setFrame(True)
        self.lineEdit_destinatario.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_destinatario.setObjectName("lineEdit_destinatario")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgba(145, 40, 109,0.1)")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(100, 210, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:rgba(145, 40, 109,0.1)")
        self.label_4.setObjectName("label_4")
        self.pushButton_transferir = QtWidgets.QPushButton(self.frame)
        self.pushButton_transferir.setGeometry(QtCore.QRect(210, 280, 111, 31))
        self.pushButton_transferir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_transferir.setToolTip("")
        self.pushButton_transferir.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0) ;\n"
"    background-color : rgba(255,255,255,0.5);\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255,255,255) ;\n"
"    background-color : rgb(0,0,0);\n"
"}")
        self.pushButton_transferir.setAutoDefault(True)
        self.pushButton_transferir.setDefault(True)
        self.pushButton_transferir.setFlat(False)
        self.pushButton_transferir.setObjectName("pushButton_transferir")
        self.Icon_Login = QtWidgets.QLabel(self.frame)
        self.Icon_Login.setEnabled(True)
        self.Icon_Login.setGeometry(QtCore.QRect(160, 40, 51, 51))
        self.Icon_Login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Icon_Login.setStyleSheet("background-color:rgb(241, 241, 241)rgb(253, 253, 253)")
        self.Icon_Login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Icon_Login.setText("")
        self.Icon_Login.setPixmap(QtGui.QPixmap("bank\img\Transfer2.png"))
        self.Icon_Login.setScaledContents(True)
        self.Icon_Login.setWordWrap(False)
        self.Icon_Login.setObjectName("Icon_Login")
        self.pushButton_voltar = QtWidgets.QPushButton(self.frame)
        self.pushButton_voltar.setGeometry(QtCore.QRect(440, 380, 75, 23))
        self.pushButton_voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_voltar.setAutoFillBackground(False)
        self.pushButton_voltar.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0) ;\n"
"    background-color : rgba(255,255,255,0.5);\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255,255,255) ;\n"
"    background-color : rgb(0,0,0);\n"
"}")
        self.pushButton_voltar.setObjectName("pushButton_voltar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_destinatario, self.lineEdit_valor)
        Form.setTabOrder(self.lineEdit_valor, self.pushButton_transferir)
        Form.setTabOrder(self.pushButton_transferir, self.pushButton_voltar)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Transferência</span></p></body></html>"))
        self.lineEdit_valor.setPlaceholderText(_translate("Form", "Ex: R$ 100.50"))
        self.lineEdit_destinatario.setPlaceholderText(_translate("Form", "Número da Conta"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">Destinatário</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">Valor</span></p></body></html>"))
        self.pushButton_transferir.setText(_translate("Form", "Transferir"))
        self.pushButton_voltar.setText(_translate("Form", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Tela_Transferencia()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
