# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_deposito.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Deposito(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        Form.setStyleSheet("background-color:rgba(145, 40, 109,0.9)")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(290, 80, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Icon_Login = QtWidgets.QLabel(Form)
        self.Icon_Login.setEnabled(True)
        self.Icon_Login.setGeometry(QtCore.QRect(220, 80, 61, 71))
        self.Icon_Login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Icon_Login.setStyleSheet("background-color:rgb(241, 241, 241)rgb(253, 253, 253)")
        self.Icon_Login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Icon_Login.setText("")
        self.Icon_Login.setPixmap(QtGui.QPixmap("bank\img\deposito2.png"))
        self.Icon_Login.setScaledContents(True)
        self.Icon_Login.setWordWrap(False)
        self.Icon_Login.setObjectName("Icon_Login")
        self.lineEdit_valor = QtWidgets.QLineEdit(Form)
        self.lineEdit_valor.setEnabled(True)
        self.lineEdit_valor.setGeometry(QtCore.QRect(240, 190, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_valor.setFont(font)
        self.lineEdit_valor.setStyleSheet("color:rgb(255,255,255)")
        self.lineEdit_valor.setText("")
        self.lineEdit_valor.setObjectName("lineEdit_valor")
        self.pushButton_depositar = QtWidgets.QPushButton(Form)
        self.pushButton_depositar.setGeometry(QtCore.QRect(260, 270, 101, 31))
        self.pushButton_depositar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_depositar.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0) ;\n"
"    background-color : rgba(255,255,255,0.5);\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255,255,255) ;\n"
"    background-color : rgb(0,0,0);\n"
"}")
        self.pushButton_depositar.setAutoDefault(True)
        self.pushButton_depositar.setDefault(True)
        self.pushButton_depositar.setObjectName("pushButton_depositar")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(170, 200, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_voltar = QtWidgets.QPushButton(Form)
        self.pushButton_voltar.setGeometry(QtCore.QRect(270, 320, 81, 21))
        self.pushButton_voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_voltar.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0) ;\n"
"    background-color : rgba(255,255,255,0.5);\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255,255,255) ;\n"
"    background-color : rgb(0,0,0);\n"
"}")
        self.pushButton_voltar.setObjectName("pushButton_voltar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_valor, self.pushButton_depositar)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">Depósito</span></p></body></html>"))
        self.lineEdit_valor.setPlaceholderText(_translate("Form", "ex:100.50"))
        self.pushButton_depositar.setText(_translate("Form", "Depositar"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Valor</span></p></body></html>"))
        self.pushButton_voltar.setText(_translate("Form", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Tela_Deposito()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
