# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_de_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 493)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(118, 0, 88)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(130, 60, 451, 381))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("background-color:rgba(145, 40, 109,0.9)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_username = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_username.setEnabled(True)
        self.lineEdit_username.setGeometry(QtCore.QRect(170, 200, 161, 21))
        self.lineEdit_username.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_username.setStyleSheet("color : rgb(255, 255, 255)")
        self.lineEdit_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_username.setDragEnabled(False)
        self.lineEdit_username.setReadOnly(False)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(70, 200, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("background-color:rgb(241, 241, 241)rgb(253, 253, 253)")
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setObjectName("label_7")
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_password.setEnabled(True)
        self.lineEdit_password.setGeometry(QtCore.QRect(170, 240, 161, 21))
        self.lineEdit_password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_password.setStyleSheet("color:rgb(255, 255, 255)")
        self.lineEdit_password.setInputMask("")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(70, 240, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("background-color:rgb(241, 241, 241)rgb(253, 253, 253)")
        self.label_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_8.setObjectName("label_8")
        self.pushButton_entrar = QtWidgets.QPushButton(self.frame)
        self.pushButton_entrar.setEnabled(True)
        self.pushButton_entrar.setGeometry(QtCore.QRect(160, 290, 121, 21))
        self.pushButton_entrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_entrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_entrar.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0) ;\n"
"    background-color : rgba(255,255,255,0.5);\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255,255,255) ;\n"
"    background-color : rgb(0,0,0);\n"
"}\n"
"")
        self.pushButton_entrar.setObjectName("pushButton_entrar")
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.frame)
        self.pushButton_cadastrar.setEnabled(True)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(160, 330, 121, 21))
        self.pushButton_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_cadastrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_cadastrar.setStyleSheet("\n"
"QPushButton{\n"
"    color: rgb(0, 0, 0) ;\n"
"    background-color : rgba(255,255,255,0.5);\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255,255,255) ;\n"
"    background-color : rgb(0,0,0);\n"
"}")
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 111, 101))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background-color:rgb(241, 241, 241)rgb(253, 253, 253)")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("bank\img\icon_login.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 120, 171, 61))
        self.label.setStyleSheet("background-color:rgb(241, 241, 241)rgb(253, 253, 253)")
        self.label.setObjectName("label")
        self.label_2.raise_()
        self.lineEdit_username.raise_()
        self.label_7.raise_()
        self.lineEdit_password.raise_()
        self.label_8.raise_()
        self.pushButton_entrar.raise_()
        self.pushButton_cadastrar.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_username, self.lineEdit_password)
        MainWindow.setTabOrder(self.lineEdit_password, self.pushButton_entrar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">USERNAME</span></p></body></html>"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "SENHA"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">PASSWORD</span></p></body></html>"))
        self.pushButton_entrar.setText(_translate("MainWindow", "ENTRAR"))
        self.pushButton_cadastrar.setText(_translate("MainWindow", "CADASTRE-SE"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">VNC BANK</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_de_Login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
